//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyRE.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappyRE.Web.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ qua.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tất.
        /// </summary>
        public static string Button_Finished {
            get {
                return ResourceManager.GetString("Button_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đồng ý.
        /// </summary>
        public static string Button_OKI {
            get {
                return ResourceManager.GetString("Button_OKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Button_Reject {
            get {
                return ResourceManager.GetString("Button_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Confirm_Arlet {
            get {
                return ResourceManager.GetString("Confirm_Arlet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string Confirm_Title {
            get {
                return ResourceManager.GetString("Confirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;title&quot;&gt;Thời hạn xuất hóa đơn:&lt;/div&gt;
        ///        &lt;div class=&quot;description&quot;&gt;
        ///            batdongsanhanhphuc.vn chỉ xuất hoá đơn VAT trong tháng. Chúng tôi không xuất hóa đơn cho tiền khuyến mãi.
        ///            &lt;br /&gt;
        ///            Để được hỗ trợ xin liên hệ 1900 6868, 028.7300 1234 (HCM), 024.7300 1234 (HN) hoặc mail &lt;a href=&quot;mailto:trogiup@batdongsanhanhphuc.vn&quot;&gt;trogiup@batdongsanhanhphuc.vn&lt;/a&gt;
        ///        &lt;/div&gt;.
        /// </summary>
        public static string Invoice_Note {
            get {
                return ResourceManager.GetString("Invoice_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string Lbl_Account_MBPay {
            get {
                return ResourceManager.GetString("Lbl_Account_MBPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string lbl_Close {
            get {
                return ResourceManager.GetString("lbl_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên hỗ trợ.
        /// </summary>
        public static string Lbl_Dash_SupportStaff {
            get {
                return ResourceManager.GetString("Lbl_Dash_SupportStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả ngày.
        /// </summary>
        public static string Lbl_Date_Common_All {
            get {
                return ResourceManager.GetString("Lbl_Date_Common_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cách đây 30 ngày.
        /// </summary>
        public static string Lbl_Date_Common_From_30 {
            get {
                return ResourceManager.GetString("Lbl_Date_Common_From_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày đến ngày.
        /// </summary>
        public static string Lbl_Date_Common_From_To {
            get {
                return ResourceManager.GetString("Lbl_Date_Common_From_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string Lbl_Date_Common_Month {
            get {
                return ResourceManager.GetString("Lbl_Date_Common_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn ngày.
        /// </summary>
        public static string Lbl_Date_Common_Selected {
            get {
                return ResourceManager.GetString("Lbl_Date_Common_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay.
        /// </summary>
        public static string Lbl_Date_Common_Today {
            get {
                return ResourceManager.GetString("Lbl_Date_Common_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuần này.
        /// </summary>
        public static string Lbl_Date_Common_Week {
            get {
                return ResourceManager.GetString("Lbl_Date_Common_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm qua.
        /// </summary>
        public static string Lbl_Date_Common_Yesterday {
            get {
                return ResourceManager.GetString("Lbl_Date_Common_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Lbl_Delete {
            get {
                return ResourceManager.GetString("Lbl_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản chính (TKC).
        /// </summary>
        public static string Lbl_MBPay_Balance_Amount {
            get {
                return ResourceManager.GetString("Lbl_MBPay_Balance_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mãi 1 (KM1).
        /// </summary>
        public static string Lbl_MBPay_Balance_Bonus1 {
            get {
                return ResourceManager.GetString("Lbl_MBPay_Balance_Bonus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến mãi 2 (KM2).
        /// </summary>
        public static string Lbl_MBPay_Balance_Bonus2 {
            get {
                return ResourceManager.GetString("Lbl_MBPay_Balance_Bonus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hôm nay.
        /// </summary>
        public static string Lbl_Today {
            get {
                return ResourceManager.GetString("Lbl_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh bạn chọn phải có dung lượng nhỏ hơn 5MB.
        /// </summary>
        public static string Msg_ProfileImage_Size_Error {
            get {
                return ResourceManager.GetString("Msg_ProfileImage_Size_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh bạn chọn không hợp lệ. chúng tôi chỉ cho phép các định dạnh sau: (.gif, .png, .jpg, .bmp).
        /// </summary>
        public static string Msg_ProfileImage_Type_Error {
            get {
                return ResourceManager.GetString("Msg_ProfileImage_Type_Error", resourceCulture);
            }
        }
    }
}
