//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyRE.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContactMogi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContactMogi() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappyRE.Web.Resources.ContactMogi", typeof(ContactMogi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trực tiếp tại các &lt;a href=&quot;{0}&quot;&gt;văn phòng giao dịch, các điểm nhận tin&lt;/a&gt; của chúng tôi.
        /// </summary>
        public static string ContactMogi_Body1 {
            get {
                return ResourceManager.GetString("ContactMogi_Body1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng đài chăm sóc khách hàng toàn quốc: &lt;b&gt;19006868&lt;/b&gt; &lt;i style=&quot;color:#656b79&quot;&gt;(cước cuộc gọi: 1.800đ/phút/cố định; 2.700đ/phút/di động)&lt;/i&gt;.
        /// </summary>
        public static string ContactMogi_Body2 {
            get {
                return ResourceManager.GetString("ContactMogi_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: &lt;a href=&quot;mailto:trogiup@batdongsanhanhphuc.vn&quot;&gt;trogiup@batdongsanhanhphuc.vn&lt;/a&gt;.
        /// </summary>
        public static string ContactMogi_Body3 {
            get {
                return ResourceManager.GetString("ContactMogi_Body3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập nội dung.
        /// </summary>
        public static string ContactMogi_ContentPlaceHolder {
            get {
                return ResourceManager.GetString("ContactMogi_ContentPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập địa chỉ email.
        /// </summary>
        public static string ContactMogi_EmailPlaceHolder {
            get {
                return ResourceManager.GetString("ContactMogi_EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quý khách hàng có thể góp ý trực tiếp tại đây:.
        /// </summary>
        public static string ContactMogi_FormTitle {
            get {
                return ResourceManager.GetString("ContactMogi_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập số điện thoại.
        /// </summary>
        public static string ContactMogi_MobilePlaceHolder {
            get {
                return ResourceManager.GetString("ContactMogi_MobilePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ với Mogi.
        /// </summary>
        public static string ContactMogi_PageHeader {
            get {
                return ResourceManager.GetString("ContactMogi_PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mọi góp ý, xin liên hệ:.
        /// </summary>
        public static string ContactMogi_Title {
            get {
                return ResourceManager.GetString("ContactMogi_Title", resourceCulture);
            }
        }
    }
}
