//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyRE.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappyRE.Web.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tin BĐS đang đăng.
        /// </summary>
        public static string AgentDetail_TotalPostedProperty {
            get {
                return ResourceManager.GetString("AgentDetail_TotalPostedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môi giới.
        /// </summary>
        public static string Home_Agent {
            get {
                return ResourceManager.GetString("Home_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua.
        /// </summary>
        public static string Home_Buy {
            get {
                return ResourceManager.GetString("Home_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá nhà mặt tiền.
        /// </summary>
        public static string Home_HousePrice_Title {
            get {
                return ResourceManager.GetString("Home_HousePrice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Home_LogIn {
            get {
                return ResourceManager.GetString("Home_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá nhà đất.
        /// </summary>
        public static string Home_MarketPrice {
            get {
                return ResourceManager.GetString("Home_MarketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toàn quốc.
        /// </summary>
        public static string Home_Msg_Location_All {
            get {
                return ResourceManager.GetString("Home_Msg_Location_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng giá.
        /// </summary>
        public static string Home_Msg_Price {
            get {
                return ResourceManager.GetString("Home_Msg_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        public static string Home_Project {
            get {
                return ResourceManager.GetString("Home_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuê.
        /// </summary>
        public static string Home_Rent {
            get {
                return ResourceManager.GetString("Home_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Home_Search {
            get {
                return ResourceManager.GetString("Home_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm mua.
        /// </summary>
        public static string Home_Search_Buy {
            get {
                return ResourceManager.GetString("Home_Search_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm thuê.
        /// </summary>
        public static string Home_Search_Rent {
            get {
                return ResourceManager.GetString("Home_Search_Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đúng nhà, đúng giá, đúng thời điểm.
        /// </summary>
        public static string Home_Slogan {
            get {
                return ResourceManager.GetString("Home_Slogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bất động sản cho thuê {0}.
        /// </summary>
        public static string Home_TopRent_Title {
            get {
                return ResourceManager.GetString("Home_TopRent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bất động sản rao bán {0}.
        /// </summary>
        public static string Home_TopSale_Title {
            get {
                return ResourceManager.GetString("Home_TopSale_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review khu vực.
        /// </summary>
        public static string Home_WardReview {
            get {
                return ResourceManager.GetString("Home_WardReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem review.
        /// </summary>
        public static string Home_WardReview_Btn {
            get {
                return ResourceManager.GetString("Home_WardReview_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá khu vực nơi bạn ở nhanh chóng và tiện lợi.
        /// </summary>
        public static string Home_WardReview_Desc01 {
            get {
                return ResourceManager.GetString("Home_WardReview_Desc01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đánh giá khu vực nơi bạn ở nhanh chóng và tiện lợi tìm kiếm hàng xóm và những người bạn.
        /// </summary>
        public static string Home_WardReview_Desc02 {
            get {
                return ResourceManager.GetString("Home_WardReview_Desc02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string Listing_Filter_All {
            get {
                return ResourceManager.GetString("Listing_Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toàn quốc.
        /// </summary>
        public static string Listing_Filter_Country {
            get {
                return ResourceManager.GetString("Listing_Filter_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        public static string Listing_Filter_Location {
            get {
                return ResourceManager.GetString("Listing_Filter_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc thêm.
        /// </summary>
        public static string Listing_Filter_More {
            get {
                return ResourceManager.GetString("Listing_Filter_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bộ lọc.
        /// </summary>
        public static string Listing_Filter_Title {
            get {
                return ResourceManager.GetString("Listing_Filter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trung bình của từng loại BĐS trong quận.
        /// </summary>
        public static string Market_Price_Avg_OnDistrict {
            get {
                return ResourceManager.GetString("Market_Price_Avg_OnDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trung bình của từng loại BĐS trên con đường.
        /// </summary>
        public static string Market_Price_Avg_OnStreet {
            get {
                return ResourceManager.GetString("Market_Price_Avg_OnStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng số lượng bất động trên con đường.
        /// </summary>
        public static string Market_Price_Total_OnStreet {
            get {
                return ResourceManager.GetString("Market_Price_Total_OnStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố.
        /// </summary>
        public static string MarketList_City {
            get {
                return ResourceManager.GetString("MarketList_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận.
        /// </summary>
        public static string MarketList_District {
            get {
                return ResourceManager.GetString("MarketList_District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quận, đường.
        /// </summary>
        public static string MarketList_DistrictOrStreet {
            get {
                return ResourceManager.GetString("MarketList_DistrictOrStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đường.
        /// </summary>
        public static string MarketList_Placeholder {
            get {
                return ResourceManager.GetString("MarketList_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng BĐS.
        /// </summary>
        public static string MarketList_PropertyNumber {
            get {
                return ResourceManager.GetString("MarketList_PropertyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoặc tìm theo quận.
        /// </summary>
        public static string MarketList_SearchDistrict {
            get {
                return ResourceManager.GetString("MarketList_SearchDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đường.
        /// </summary>
        public static string MarketList_StreetName {
            get {
                return ResourceManager.GetString("MarketList_StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng đường.
        /// </summary>
        public static string MarketList_StreetNumber {
            get {
                return ResourceManager.GetString("MarketList_StreetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tham khảo &lt;span&gt;giá nhà đất&lt;/span&gt; tại Hà Nội &amp; Hồ Chí Minh.
        /// </summary>
        public static string MarketList_Title {
            get {
                return ResourceManager.GetString("MarketList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trung bình.
        /// </summary>
        public static string MarketPrice_AvgPrice {
            get {
                return ResourceManager.GetString("MarketPrice_AvgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá {0} {1} theo tháng.
        /// </summary>
        public static string MarketPrice_Detail_Title {
            get {
                return ResourceManager.GetString("MarketPrice_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử giá.
        /// </summary>
        public static string MarketPrice_History {
            get {
                return ResourceManager.GetString("MarketPrice_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số nhà.
        /// </summary>
        public static string MarketPrice_History_Address {
            get {
                return ResourceManager.GetString("MarketPrice_History_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diện tích.
        /// </summary>
        public static string MarketPrice_History_Area {
            get {
                return ResourceManager.GetString("MarketPrice_History_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng.
        /// </summary>
        public static string MarketPrice_History_Date {
            get {
                return ResourceManager.GetString("MarketPrice_History_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string MarketPrice_History_Desc {
            get {
                return ResourceManager.GetString("MarketPrice_History_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày rao cuối.
        /// </summary>
        public static string MarketPrice_History_EndDate {
            get {
                return ResourceManager.GetString("MarketPrice_History_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá rao.
        /// </summary>
        public static string MarketPrice_History_Price {
            get {
                return ResourceManager.GetString("MarketPrice_History_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại/Kiểu.
        /// </summary>
        public static string MarketPrice_History_PropertyType {
            get {
                return ResourceManager.GetString("MarketPrice_History_PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguồn.
        /// </summary>
        public static string MarketPrice_History_Source {
            get {
                return ResourceManager.GetString("MarketPrice_History_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngày.
        /// </summary>
        public static string MarketPrice_History_Time {
            get {
                return ResourceManager.GetString("MarketPrice_History_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm lịch sử giá BĐS này qua các năm.
        /// </summary>
        public static string MarketPrice_History_TimeLine {
            get {
                return ResourceManager.GetString("MarketPrice_History_TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử giá.
        /// </summary>
        public static string MarketPrice_HistoryPrice {
            get {
                return ResourceManager.GetString("MarketPrice_HistoryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 tháng gần đây.
        /// </summary>
        public static string MarketPrice_LastOneMonth {
            get {
                return ResourceManager.GetString("MarketPrice_LastOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Tháng gần đây.
        /// </summary>
        public static string MarketPrice_LastThreeMonth {
            get {
                return ResourceManager.GetString("MarketPrice_LastThreeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá cao nhất.
        /// </summary>
        public static string MarketPrice_MaxPtrice {
            get {
                return ResourceManager.GetString("MarketPrice_MaxPtrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá thấp nhất.
        /// </summary>
        public static string MarketPrice_MinPrice {
            get {
                return ResourceManager.GetString("MarketPrice_MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trung bình.
        /// </summary>
        public static string MarketPrice_Property_AvgPrice {
            get {
                return ResourceManager.GetString("MarketPrice_Property_AvgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem lịch sử giá các BĐS trên đường {0}.
        /// </summary>
        public static string MarketPrice_Property_Title {
            get {
                return ResourceManager.GetString("MarketPrice_Property_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá nhà đất đường trong {0}.
        /// </summary>
        public static string MarketPrice_Street_Title {
            get {
                return ResourceManager.GetString("MarketPrice_Street_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá nhà đất.
        /// </summary>
        public static string MarketPrice_Title {
            get {
                return ResourceManager.GetString("MarketPrice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng BĐS.
        /// </summary>
        public static string MarketPrice_TotalProp {
            get {
                return ResourceManager.GetString("MarketPrice_TotalProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cảm ơn Bạn đã gửi phản hồi.
        /// </summary>
        public static string Msg_ThankYou_Feedback {
            get {
                return ResourceManager.GetString("Msg_ThankYou_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string Msg_ViewMore {
            get {
                return ResourceManager.GetString("Msg_ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Project_Desc {
            get {
                return ResourceManager.GetString("Project_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn giao: {0}.
        /// </summary>
        public static string Project_EndDate {
            get {
                return ResourceManager.GetString("Project_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bàn giao.
        /// </summary>
        public static string Project_EndDate02 {
            get {
                return ResourceManager.GetString("Project_EndDate02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        public static string Project_Info {
            get {
                return ResourceManager.GetString("Project_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đầu tư.
        /// </summary>
        public static string Project_Investor {
            get {
                return ResourceManager.GetString("Project_Investor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản đồ.
        /// </summary>
        public static string Project_Map {
            get {
                return ResourceManager.GetString("Project_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string Project_Price {
            get {
                return ResourceManager.GetString("Project_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bất động sản đang bán.
        /// </summary>
        public static string Project_RelativeProps {
            get {
                return ResourceManager.GetString("Project_RelativeProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà mẫu.
        /// </summary>
        public static string Project_SampleHouse {
            get {
                return ResourceManager.GetString("Project_SampleHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mua bán bất động sản - dự án mới tại {0}.
        /// </summary>
        public static string Project_SearchResult {
            get {
                return ResourceManager.GetString("Project_SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án nỗi bật.
        /// </summary>
        public static string Project_SearchResult2 {
            get {
                return ResourceManager.GetString("Project_SearchResult2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string Project_ViewMore {
            get {
                return ResourceManager.GetString("Project_ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm mua.
        /// </summary>
        public static string ProjectDetail_RelativeProps {
            get {
                return ResourceManager.GetString("ProjectDetail_RelativeProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà Mẫu.
        /// </summary>
        public static string ProjectDetail_SampleHouse {
            get {
                return ResourceManager.GetString("ProjectDetail_SampleHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string ProjectDetail_Summary {
            get {
                return ResourceManager.GetString("ProjectDetail_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiện ích.
        /// </summary>
        public static string ProjectDetail_Utils {
            get {
                return ResourceManager.GetString("ProjectDetail_Utils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string ProjectDetail_ViewMore {
            get {
                return ResourceManager.GetString("ProjectDetail_ViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review {0}.
        /// </summary>
        public static string ReviewWard_SEO_DCTitle {
            get {
                return ResourceManager.GetString("ReviewWard_SEO_DCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review {0} chân thật, chi tiết, cụ thể giá nhà đất, trường học, nhiều tiện ích hấp dẫn, những thông giá trị cần biết.
        /// </summary>
        public static string ReviewWard_SEO_Desc {
            get {
                return ResourceManager.GetString("ReviewWard_SEO_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VN-{0}.
        /// </summary>
        public static string ReviewWard_SEO_georegion {
            get {
                return ResourceManager.GetString("ReviewWard_SEO_georegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review {0}.
        /// </summary>
        public static string ReviewWard_SEO_Title {
            get {
                return ResourceManager.GetString("ReviewWard_SEO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chia sẻ thông tin này cho bạn bè:.
        /// </summary>
        public static string Social_Share_Title {
            get {
                return ResourceManager.GetString("Social_Share_Title", resourceCulture);
            }
        }
    }
}
