//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mogi.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message_en_US_Designer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message_en_US_Designer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mogi.Web.Resources.Message.en-US.Designer", typeof(Message_en_US_Designer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average price on district.
        /// </summary>
        internal static string Market_Price_Avg_OnDistrict {
            get {
                return ResourceManager.GetString("Market_Price_Avg_OnDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average price on street.
        /// </summary>
        internal static string Market_Price_Avg_OnStreet {
            get {
                return ResourceManager.GetString("Market_Price_Avg_OnStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sale on street.
        /// </summary>
        internal static string Market_Price_Total_OnStreet {
            get {
                return ResourceManager.GetString("Market_Price_Total_OnStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Price.
        /// </summary>
        internal static string MarketPrice_AvgPrice {
            get {
                return ResourceManager.GetString("MarketPrice_AvgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string MarketPrice_LastOneMonth {
            get {
                return ResourceManager.GetString("MarketPrice_LastOneMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 months.
        /// </summary>
        internal static string MarketPrice_LastThreeMonth {
            get {
                return ResourceManager.GetString("MarketPrice_LastThreeMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Price.
        /// </summary>
        internal static string MarketPrice_MaxPtrice {
            get {
                return ResourceManager.GetString("MarketPrice_MaxPtrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest Price.
        /// </summary>
        internal static string MarketPrice_MinPrice {
            get {
                return ResourceManager.GetString("MarketPrice_MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Price.
        /// </summary>
        internal static string MarketPrice_Property_AvgPrice {
            get {
                return ResourceManager.GetString("MarketPrice_Property_AvgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Price.
        /// </summary>
        internal static string MarketPrice_Title {
            get {
                return ResourceManager.GetString("MarketPrice_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string MarketPrice_TotalProp {
            get {
                return ResourceManager.GetString("MarketPrice_TotalProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this infomation to your friend:.
        /// </summary>
        internal static string Social_Share_Title {
            get {
                return ResourceManager.GetString("Social_Share_Title", resourceCulture);
            }
        }
    }
}
